# Generated by Django 5.0.7 on 2024-08-10 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_roles", "0001_initial"),
        ("app_servers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="members",
            field=models.ManyToManyField(related_name="roles", to="app_servers.member"),
        ),
        migrations.AddField(
            model_name="role",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="app_servers.server",
            ),
        ),
    ]
