# Generated by Django 5.0.7 on 2024-08-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_roles", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_manage_server", models.BooleanField(default=False)),
                ("can_manage_roles", models.BooleanField(default=False)),
                ("can_manage_channels", models.BooleanField(default=False)),
                ("can_manage_messages", models.BooleanField(default=False)),
                ("can_send_messages", models.BooleanField(default=False)),
                ("can_send_attachments", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.OneToOneField(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_roles.permissions",
            ),
            preserve_default=False,
        ),
    ]
