# Generated by Django 5.0.7 on 2024-08-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_roles", "0003_role_permissions"),
        ("app_servers", "0004_member_permissions_server_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="app_servers.member"
            ),
        ),
    ]
