# Generated by Django 5.0.7 on 2024-08-05 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emoji", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emoji",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
