# Generated by Django 5.0.7 on 2024-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emoji", "0002_emoji_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="emoji",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
