# Generated by Django 5.0.7 on 2024-08-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_messages", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
