# Generated by Django 5.0.7 on 2024-08-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_messages", "0003_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="filename",
            field=models.CharField(default="file.txt", max_length=256),
            preserve_default=False,
        ),
    ]
