# Generated by Django 5.0.7 on 2024-08-06 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0003_remove_server_owner_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="server",
        ),
        migrations.AddField(
            model_name="server",
            name="owner",
            field=models.OneToOneField(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="servers.owner",
            ),
            preserve_default=False,
        ),
    ]
