# Generated by Django 5.0.7 on 2024-08-08 00:56

import django.db.models.deletion
import strife.apps.servers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0004_remove_owner_server_server_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="servers.server",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_objs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=strife.apps.servers.models.server_image_path,
            ),
        ),
    ]
