# Generated by Django 5.0.7 on 2024-08-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emoji", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=256)),
                (
                    "emoji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emoji.emoji"
                    ),
                ),
            ],
        ),
    ]
