# Generated by Django 5.0.7 on 2024-08-05 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reactions", "0001_initial"),
        ("user_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_messages.message"
            ),
        ),
    ]
