# Generated by Django 5.0.7 on 2024-08-05 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="description",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="name",
        ),
        migrations.AddField(
            model_name="reaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
