# Generated by Django 5.0.7 on 2024-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0004_remove_reaction_description_remove_reaction_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
