# Generated by Django 5.0.7 on 2024-08-05 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageable",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="servers.server"
            ),
        ),
        migrations.CreateModel(
            name="StageChannel",
            fields=[
                (
                    "speakable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="channels.speakable",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("channels.speakable",),
        ),
        migrations.CreateModel(
            name="VoiceChannel",
            fields=[
                (
                    "speakable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="channels.speakable",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("channels.speakable",),
        ),
        migrations.AddField(
            model_name="speakable",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="speakable",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="servers.server"
            ),
        ),
    ]
