# Generated by Django 5.0.7 on 2024-08-05 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_messageable_created_at_stagechannel_created_at_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("servers", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stagechannel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="stagechannel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="stagechannel",
            name="id",
        ),
        migrations.RemoveField(
            model_name="stagechannel",
            name="name",
        ),
        migrations.RemoveField(
            model_name="stagechannel",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="stagechannel",
            name="server",
        ),
        migrations.RemoveField(
            model_name="voicechannel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="voicechannel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="voicechannel",
            name="id",
        ),
        migrations.RemoveField(
            model_name="voicechannel",
            name="name",
        ),
        migrations.RemoveField(
            model_name="voicechannel",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="voicechannel",
            name="server",
        ),
        migrations.CreateModel(
            name="Speakable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="servers.server"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="stagechannel",
            name="speakable_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="channels.speakable",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voicechannel",
            name="speakable_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="channels.speakable",
            ),
            preserve_default=False,
        ),
    ]
