# Generated by Django 5.0.7 on 2024-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0004_remove_stagechannel_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageable",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="speakable",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
