# Generated by Django 5.0.7 on 2024-08-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_manage_server", models.BooleanField(default=False)),
                ("can_manage_roles", models.BooleanField(default=False)),
                ("can_manage_channels", models.BooleanField(default=False)),
                ("can_manage_messages", models.BooleanField(default=False)),
                ("can_send_messages", models.BooleanField(default=False)),
                ("can_send_attachments", models.BooleanField(default=False)),
            ],
        ),
    ]
