# Generated by Django 5.0.7 on 2024-08-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_permissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissions",
            options={"verbose_name_plural": "Permissions"},
        ),
    ]
